spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_db
    username: learning
    password: learning
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

